### ISSUE TITLE
Custom corners and top and bottom dimension

### ISSUE THREAD

**Issue by nebulorum** [wbu/drawer_organizer#11]
I've been playing with the SCAD because I'll need a cutout for a screw at the corner of my otherwise straight edged drawers.  I found a way to make one side of the corner longer, and then subtract a shape for the notch. Any easier way to do this?

But looking at the source I notices you can vary the bottom and top width. Any specific reason for 12mm and 5mm. Could I go thinner? My drawers are not super large wonder how thin I could go...

Another final questions, have you ever created part on other CAD tools that can interface with the corners? In one of my drawers I was considering a full width container for some objects, a bit like the Gridfinity tools holders. And reference document for that?

**Comment by wbu** [comment]
> I've been playing with the SCAD because I'll need a cutout for a screw at the corner of my otherwise straight edged drawers. I found a way to make one side of the corner longer, and then subtract a shape for the notch. Any easier way to do this?

OpenSCAD is all about adding and subtracting volumes. I don't think it gets any easier than that.

> But looking at the source I notices you can vary the bottom and top width. Any specific reason for 12mm and 5mm. Could I go thinner? My drawers are not super large wonder how thin I could go...

If I remember correctly, I might have taken measurement on one of my commercial drawer divider. So it's mostly esthetics. If you make it much thinner, the pieces might bend more easily and the connections also become smaller. But you can try anything you like. I even considered the possibility to have a wider top than bottom. This needs a special case for the parametric design, so that you can still put the pieces together. Anyway, I never really tested this.

> Another final questions, have you ever created part on other CAD tools that can interface with the corners? In one of my drawers I was considering a full width container for some objects, a bit like the Gridfinity tools holders. And reference document for that?

No. For this project I only used OpenSCAD. But it might be possible to import STL files in other CAD programs or redesign the needed pieces. They are not that complicated after all. When I do things like that, I often import the STL only as a reference and design my pieces from scratch. This way it's easy to check for any differences.

**Comment by nebulorum** [comment]
Thanks for the insight and for the design.
