### ISSUE TITLE
Boarder Straight Connector leans to one side

### ISSUE THREAD

**Issue by Datafreak** [wbu/drawer_organizer#2]
Hi,

it looks like the Boarder Straight Connector is somehow broken.
It leans to one side:
![Boarder Straight Connector](https://user-images.githubusercontent.com/2600684/103446165-eb2a3680-4c7c-11eb-8eab-13da9b149936.png)

It is possible to fix this?

Best Regards,
Datafreak

**Comment by wbu** [comment]
That is intentional. You can change it with the border_overhang parameter. According to your screenshot, you use the default of 13mm. Setting it to zero will create border pieces with one straight side (outside) and one slightly slanted (inside).

Is that what you meant, or do you need any other "fix"? :)

**Comment by Datafreak** [comment]
Ah, thank you for your Feedback. This explains it.
Than this was an invalid request and I will close this issue.
